import pandas as pd 
f=open("bankoutput.txt","w") 
df = pd.read_csv('Resources/budget_data.csv')
print("Financial Analysis")
f.write("Financial Analysis\n")
print("----------------------------")
f.write("----------------------------\n")
print("Total Months:",df.shape[0])
f.write("Total Months:"+str(df.shape[0])+"\n")
total = df['Profit/Losses'].sum() 
print("Total:$",total) 
f.write("Total:$"+str(total)+"\n")
df['shifted']=df['Profit/Losses'].shift(1)
df['difference']=df['Profit/Losses']-df['shifted']
averagechange = df['difference'].mean() 
print("Average:$",format(averagechange,'.0f'))
f.write("Average:$"+str(format(averagechange,'.0f'))+"\n")
max = df['difference'].max() 
maxindex=df['difference'].idxmax(axis=1) 
# print(maxindex)
#print(df['Date'].iloc[maxindex])
#f.write(str(df['Date'].iloc[maxindex]))
print("Greatest Increase in Profits:$",df['Date'].iloc[maxindex],max) 
f.write("Greatest Increase in Profits:$"+str(df['Date'].iloc[maxindex])+str(max)+"\n") 
min = df['difference'].min() 
minindex=df['difference'].idxmin(axis=1)
print("Greatest Difference in Profits:$",df['Date'].iloc[minindex],min) 
f.write("Greatest Difference in Profits:$"+str(df['Date'].iloc[minindex])+str(min)) 